usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /
    
#pagina_ayuda:
#    pattern: /ayuda
#    defaults: { _controller: OfertaBundle:Default:ayuda }

#OfertaBundle:
#    resource: "@OfertaBundle/Resources/config/routing.yml"
#    prefix:   /

pagina_estatica:
    pattern: /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    
_pagina_estatica:
    pattern: /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    
#portada:
#    pattern: /
#    defaults: { _controller: OfertaBundle:Default:portada }
    
# Ruta completa de la portada (con el slug de la ciudad)
portada:
    pattern: /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }
# Ruta simple de la portada
_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada }








